version: '1.1.3.{build}'

environment:
  nuget_apikey:
    secure: AWSfDUQgVaMF1fhfsaVx5Hy/qIa9lwyPwXQ9kYTYUJV4qdEeFHMIggk2COOD6DH2

image: Visual Studio 2017

init:
  - ps: |
      if ( $env:appveyor_repo_tag_name ) {
        $env:APPVEYOR_BUILD_VERSION = "$( $env:appveyor_repo_tag_name )"
        Update-AppveyorBuild -Version $env:APPVEYOR_BUILD_VERSION
      }

install:
  - ps: Install-Module InvokeBuild -Force
  - ps: Install-Module Pester -Force -SkipPublisherCheck
  - ps: Install-Module PlatyPS -Force
  - docker version

platform:
  - x64

before_build:
  -ps: Invoke-Build UpdateDocs

build_script:
  - ps: Invoke-Build Build

test_script:
  - ps: |
      $testResultsFile = ".\TestsResults.xml"
      $res = Invoke-Pester "$env:APPVEYOR_BUILD_FOLDER\src\Test" -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
      if ($res.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }

# branch specific configuration
for:

- # master
  branches:
    only:
      - master

  deploy_script:
    - ps: Invoke-Build Publish