on:
  push:
    branches: [ develop, bugfix/*, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install build dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild, platyPs -ErrorAction Stop

      - name: Create build
        shell: pwsh
        run: Invoke-Build Build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          path: publish
          name: ${{ matrix.os }}-build
  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          path: publish
          name: ${{ matrix.os }}-build

      - name: Run tests
        shell: pwsh
        run: |
          $config = New-PesterConfiguration @{
            'Run.Path' = 'test'
            'Run.Exit' = $true
            'TestResult.Enabled' = $true
            'CodeCoverage.Enabled' = $true
          }
          Invoke-Pester -Configuration $config

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-test-results
          path: testResults.xml

      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-test-coverage
          path: coverage.xml
